## data
train_file: /home/lzx/PycharmProject/myAPRproject/DPR/dpr_train.json
dev_file: /home/lzx/PycharmProject/myAPRproject/DPR/dpr_dev.json


## training
base_model: bert-base-uncased
per_device_train_batch_size: 32
per_device_eval_batch_size: 16
adam_eps: 1.0e-8
weight_decay: 0.0
max_grad_norm: 2.0
lr: 2.0e-5
warmup_steps: 1237
max_train_epochs: 30
seed: 19980406
gradient_accumulation_steps: 1
val_check_interval: 3.0
